blank_issues_enabled: true
contact_links:
  - name: Quizfreely Discord
    url: https://quizfreely.com/discord
    about: i forgor
  - name: Quizfreely GitHub Discussions
    url: https://github.com/ehanahamed/quizfreely/discussions
    about: i forgor
