on:
  workflow_dispatch:
jobs:
  deploy_site:
    name: Deploy Site Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm install
      - name: Minify
        run: npm run minify-site
      - name: Deploy Site
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
